'use strict';
const $=s=>document.querySelector(s);
const main=$('#main');
let book,assets,current=null,routeToken=0,scrollTimer,offlineRunning=false,offlineCancel=false,installPrompt,navigationSaved=false;
const readStore=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback;}catch{return fallback;}};
const writeStore=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
let prefs=readStore('buhuan-settings',{font:20,line:1.9,theme:'paper'});
prefs.font=Math.min(30,Math.max(16,Number(prefs.font)||20));
prefs.line=[1.6,1.9,2.2].includes(Number(prefs.line))?Number(prefs.line):1.9;
prefs.theme=['paper','white','green','night'].includes(prefs.theme)?prefs.theme:'paper';
function applyPrefs(){document.body.dataset.theme=prefs.theme;document.documentElement.style.setProperty('--font',prefs.font+'px');document.documentElement.style.setProperty('--leading',prefs.line);$('#font-output').value=prefs.font;$('#font-minus').disabled=prefs.font<=16;$('#font-plus').disabled=prefs.font>=30;$('#line-height').value=prefs.line;document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===prefs.theme)));$('meta[name="theme-color"]').content=getComputedStyle(document.body).getPropertyValue('--bg').trim();writeStore('buhuan-settings',prefs);}
$('#settings-open').onclick=()=>$('#settings').showModal();
$('#font-minus').onclick=()=>{prefs.font=Math.max(16,prefs.font-2);applyPrefs();};
$('#font-plus').onclick=()=>{prefs.font=Math.min(30,prefs.font+2);applyPrefs();};
$('#line-height').onchange=e=>{prefs.line=Number(e.target.value);applyPrefs();};
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{prefs.theme=b.dataset.theme;applyPrefs();});
applyPrefs();
function node(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x;}
function link(text,hash,cls){const x=node('a',cls,text);x.href='#'+hash;return x;}
function imageFor(id,alt,lazy=true){const a=assets.get(id);if(!a)throw Error('图片索引缺失');const x=node('img');x.src=a.path;x.alt=alt;x.width=a.width;x.height=a.height;x.loading=lazy?'lazy':'eager';x.decoding='async';x.dataset.portrait=String(a.height>a.width);return x;}
async function json(path){const r=await fetch(path);if(!r.ok)throw Error('内容尚未准备完成');return r.json();}
function showHome(){const section=node('section','home');const wrap=node('div','cover-wrap');const cover=imageFor(book.coverAssetId,'《不还》原稿封面',false);cover.className='cover';wrap.append(cover);const copy=node('div','home-copy');copy.append(node('div','eyebrow','长篇小说'),node('h1','','不还'),node('p','description',book.description),node('p','source','摘自前言'));const meta=node('div','meta');meta.append(node('span','',book.stats.volumeCount+' 卷'),node('span','',book.stats.chapterCount+' 章'),node('span','',Math.round(book.stats.bodyNonWhitespaceChars/10000)+' 万字（含标点）'));copy.append(meta);const actions=node('div','actions');const pos=readStore('buhuan-progress',null);if(pos&&book.chapters.some(c=>c.id===pos.id)){actions.append(link('继续阅读','read/'+pos.id,'button primary'));actions.append(link('从头开始','read/c001?start','button'));const c=book.chapters.find(c=>c.id===pos.id);copy.append(node('p','resume-detail','上次读到：'+c.label));}else actions.append(link('开始阅读','read/c001','button primary'));actions.append(link('章节目录','toc','button'));copy.append(actions);section.append(wrap,copy);main.replaceChildren(section);document.title='不还 · 阅读';}
function showToc(){const section=node('section','toc');section.append(node('h1','page-heading','章节目录'));const extras=node('div','toc-intro');extras.append(link('前言','read/preface'),link('后记','read/afterword'));section.append(extras);const saved=readStore('buhuan-progress',null);book.volumes.forEach(v=>{const group=node('section','volume');const head=node('div','volume-header');head.append(node('h2','',v.label),node('span','',`${v.start}–${v.end} 章`));group.append(head);const grid=node('div','chapter-grid');book.chapters.filter(c=>c.volumeId===v.id).forEach(c=>{const a=link(c.label,'read/'+c.id,'chapter-link'+(saved?.id===c.id?' current':''));if(saved?.id===c.id)a.setAttribute('aria-current','location');grid.append(a);});group.append(grid);section.append(group);});main.replaceChildren(section);document.title='章节目录 · 不还';}
function positionOffset(){return document.querySelector('.site-header').getBoundingClientRect().height+12;}
function savePosition(){if(!current||!current.id.startsWith('c'))return;const nodes=[...document.querySelectorAll('.reader-content [data-block]')];if(!nodes.length)return;const offset=positionOffset();const anchor=nodes.find(x=>x.getBoundingClientRect().bottom>offset)||nodes.at(-1);const rect=anchor.getBoundingClientRect();writeStore('buhuan-progress',{id:current.id,block:Number(anchor.dataset.block),fraction:Math.max(0,Math.min(1,(offset-rect.top)/Math.max(1,rect.height))),updatedAt:Date.now()});}
async function showReader(id,token,start){const item=book.chapters.find(c=>c.id===id)||book.extras.find(c=>c.id===id);if(!item){location.hash='toc';return;}main.replaceChildren(node('p','loading','正在打开章节…'));const data=await json(item.path);if(token!==routeToken)return;const section=node('article','reader');const top=node('div','reader-top');top.append(link('返回目录','toc'),node('span','',book.volumes.find(v=>v.id===item.volumeId)?.label||'不还'));section.append(top,node('h1','',item.label||item.title));const content=node('div','reader-content');data.blocks.forEach((b,i)=>{let x;if(b.type==='paragraph'){x=node('p','',b.text);}else{x=node('figure');x.append(imageFor(b.assetId,`${item.label||item.title} 插图`,i>1));}x.dataset.block=i;content.append(x);});section.append(content);const bottom=node('nav','chapter-nav');bottom.setAttribute('aria-label','章节导航');const order=['preface',...book.chapters.map(c=>c.id),'afterword'];const idx=order.indexOf(id);bottom.append(idx>0?link('上一章','read/'+order[idx-1]):node('span','disabled','上一章'),link('目录','toc'),idx<order.length-1?link('下一章','read/'+order[idx+1]):node('span','disabled','下一章'));section.append(bottom);main.replaceChildren(section);current=item;document.title=(item.label||item.title)+' · 不还';const pos=readStore('buhuan-progress',null);if(!start&&pos?.id===id){const target=content.querySelector(`[data-block="${Math.max(0,Math.floor(pos.block))}"]`);if(target){await new Promise(requestAnimationFrame);if(token!==routeToken)return;window.scrollTo(0,window.scrollY+target.getBoundingClientRect().top+target.offsetHeight*(Number(pos.fraction)||0)-positionOffset());}}if(id.startsWith('c'))savePosition();}
function saveBeforeNavigation(e){const a=e.target.closest?.('a[href^="#"]');if(a&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&a.hash!==location.hash){savePosition();navigationSaved=true;}}
document.addEventListener('click',saveBeforeNavigation,true);
document.addEventListener('keydown',e=>{if(e.key==='Enter')saveBeforeNavigation(e);},true);
async function route(){if(!navigationSaved)savePosition();navigationSaved=false;current=null;const token=++routeToken;const hash=location.hash.slice(1)||'home';window.scrollTo(0,0);try{if(hash==='home')showHome();else if(hash==='toc')showToc();else if(hash.startsWith('read/')){const [id,q]=hash.slice(5).split('?');await showReader(id,token,q==='start');}else{location.hash='home';return;}}catch{if(token!==routeToken)return;const e=node('section','error');e.append(node('h1','','这一页还未下载'),node('p','','连接网络后重试，或返回已经缓存的章节。'),link('返回目录','toc','button'));main.replaceChildren(e);}if(token===routeToken)main.focus({preventScroll:true});}
window.addEventListener('hashchange',route);window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(savePosition,250);},{passive:true});window.addEventListener('pagehide',savePosition);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});
$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}};
window.addEventListener('appinstalled',()=>{$('#install').hidden=true;});
const state=$('#offline-state'),progress=$('#offline-progress'),toggle=$('#offline-toggle');
let fileList=[],contentCacheName='';
async function prepareOffline(){if(offlineRunning)return;offlineRunning=true;offlineCancel=false;toggle.hidden=false;toggle.textContent='暂停';progress.hidden=false;let done=0,failed=0;try{const cache=await caches.open(contentCacheName);const queue=[];for(const file of fileList){const hit=await cache.match(new URL(file,document.baseURI));if(hit?.ok)done++;else queue.push(file);}const update=()=>{progress.value=Math.round(done/fileList.length*100);state.textContent=`离线准备 ${progress.value}% · 全书约 ${Math.ceil((book.stats.webImageBytes+book.stats.chapterDataBytes)/1000000)} MB`;};update();let index=0;async function worker(){while(index<queue.length&&!offlineCancel){const file=queue[index++];try{const url=new URL(file,document.baseURI);const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('下载失败');await cache.put(url,r);done++;update();}catch{failed++;}}}await Promise.all([worker(),worker(),worker()]);if(offlineCancel){state.textContent=`离线准备已暂停 · ${progress.value}%`;toggle.textContent='继续';}else if(failed||done!==fileList.length){state.textContent=`离线内容未完整 · 已准备 ${done}/${fileList.length} 项`;toggle.textContent='重试';}else{state.textContent='全书已准备好，可离线阅读';progress.hidden=true;toggle.hidden=true;const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('buhuan-content-')&&k!==contentCacheName).map(k=>caches.delete(k)));}}catch(e){state.textContent='离线准备未完成，请检查设备空间与网络';toggle.textContent='重试';}finally{offlineRunning=false;}}
toggle.onclick=()=>{if(offlineRunning){offlineCancel=true;toggle.textContent='正在暂停…';}else prepareOffline();};
async function initOffline(){if(!('serviceWorker'in navigator)||!window.isSecureContext){state.textContent='此环境可在线阅读；离线功能需要 HTTPS 或本机预览';return;}try{await navigator.serviceWorker.register('sw.js',{scope:'./'});await navigator.serviceWorker.ready;const manifest=await json('offline-files.json');fileList=manifest.files;contentCacheName=manifest.cacheName;if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});$('#install-note').hidden=!/iPhone|iPad/.test(navigator.userAgent);prepareOffline();}catch{state.textContent='离线功能暂未启动，请连接网络后刷新';}}
async function init(){try{book=await json('data/book.json');assets=new Map(book.assets.map(a=>[a.id,a]));await route();initOffline();}catch{const e=node('section','error');e.append(node('h1','','暂时无法打开《不还》'),node('p','','请连接网络后刷新；本地文件需要通过预览服务打开。'));main.replaceChildren(e);state.textContent='内容加载失败';}}
init();

